### PR TITLE
Extracted Apiarist Armor checking methods to API so addons can use them more conveniently.

### PR DESCRIPTION
**Pull request by Vexatos**
~~Also provided legacy methods to not break compatibility with older mods.~~

This needs to be merged before ForestryMC/ForestryMC#836 is being merged.

If you don't like this helper class as an inner class, tell me and I'll extract it to a separate class.

### CODE REVIEW

**Comment by mezz** [comment]
This is a good idea but I don't like having implementation code in the API.
The pattern I've been using is to create an interface (`IArmorApiaristHelper` in this case), and then have a public static instance in the API's Manager class. There are a few like that in `BeeManager.java`. Then all the implementation is hidden in Forestry and bug fixes don't need to change the API.

**Comment by Vexatos** [comment]
In that case, it won't be possible to have legacy support for `wearsHelmet` etc. anymore. I guess I need to break that then.

**Comment by Vexatos** [comment]
Done. Does it look fine now?

**Comment by mezz** [comment]
Looks good, thanks! 
Last thing is to bump the API version number but I can do that myself when I merge it.

**Comment by mezz** [comment]
Merged here https://github.com/ForestryMC/ForestryAPI/commit/d2a73f85e656151cf6f46d9eb2d997087ba26f33

**Pull request closed without merging**
